# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 09:49
from __future__ import unicode_literals
from __future__ import absolute_import

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socrates_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socratesuser',
            name='is_console_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='socratesuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
